from . import models
from . import wizards


def _post_install_hook(cr, registry):
    """Hook ejecutado después de la instalación del módulo - Crea las leyendas de indicadores"""
    from odoo import api
    env = api.Environment(cr, 1, {})

    legends_data = [
        {
            'name': 'Margen Neto',
            'code': 'net_margin',
            'category': 'profitability',
            'formula': 'Ganancia Neta / Ingresos Totales × 100',
            'description': 'Mide el porcentaje de cada peso de ventas que queda como ganancia después de todos los gastos. Indica la eficiencia operativa general de la empresa.',
            'unit': '%',
            'excellent_min': 15, 'excellent_max': 100,
            'excellent_description': 'Excelente: La empresa retiene más del 15% de sus ingresos como ganancia. Muy saludable.',
            'good_min': 8, 'good_max': 14.99,
            'good_description': 'Bueno: La empresa retiene entre 8-14% de sus ingresos. Operación normal y saludable.',
            'fair_min': 2, 'fair_max': 7.99,
            'fair_description': 'Regular: La empresa retiene 2-7% de sus ingresos. Márgenes justos, revise costos.',
            'poor_min': -100, 'poor_max': 1.99,
            'poor_description': 'Deficiente: La empresa retiene menos del 2% o está operando con pérdidas. Acción urgente requerida.',
            'improvement_tips': '• Reducir costos operacionales\n• Aumentar precios de ventas\n• Mejorar eficiencia en producción\n• Eliminar gastos no esenciales\n• Aumentar volumen de ventas con costos fijos',
            'sequence': 1,
        },
        {
            'name': 'Margen Bruto',
            'code': 'gross_margin',
            'category': 'profitability',
            'formula': 'Ganancia Bruta / Ingresos Totales × 100',
            'description': 'Mide el porcentaje de ingresos que queda después de restar el costo de ventas. Indica la eficiencia en la producción o compra de productos.',
            'unit': '%',
            'excellent_min': 40, 'excellent_max': 100,
            'excellent_description': 'Excelente: Ganancia bruta superior al 40%. Muy buena eficiencia productiva.',
            'good_min': 25, 'good_max': 39.99,
            'good_description': 'Bueno: Ganancia bruta entre 25-39%. Normal para la mayoría de negocios.',
            'fair_min': 15, 'fair_max': 24.99,
            'fair_description': 'Regular: Ganancia bruta entre 15-24%. Márgenes ajustados, revise costos de producción.',
            'poor_min': -100, 'poor_max': 14.99,
            'poor_description': 'Deficiente: Ganancia bruta inferior al 15%. Costos muy altos o precios muy bajos.',
            'improvement_tips': '• Negociar mejores precios con proveedores\n• Mejorar procesos productivos\n• Reducir desperdicio en producción\n• Aumentar precios de venta\n• Cambiar mix de productos hacia margen más alto',
            'sequence': 2,
        },
        {
            'name': 'Margen Operacional',
            'code': 'operating_margin',
            'category': 'profitability',
            'formula': 'Ganancia Operacional / Ingresos Totales × 100',
            'description': 'Mide el porcentaje de ingresos que queda como ganancia operacional. Muestra la rentabilidad de las operaciones principales sin considerar financiamiento.',
            'unit': '%',
            'excellent_min': 12, 'excellent_max': 100,
            'excellent_description': 'Excelente: Margen operacional superior al 12%. Operación muy eficiente.',
            'good_min': 6, 'good_max': 11.99,
            'good_description': 'Bueno: Margen operacional entre 6-11%. Normal y saludable.',
            'fair_min': 2, 'fair_max': 5.99,
            'fair_description': 'Regular: Margen operacional entre 2-5%. Gastos operacionales altos.',
            'poor_min': -100, 'poor_max': 1.99,
            'poor_description': 'Deficiente: Margen operacional menor al 2% o negativo. Gastos operacionales fuera de control.',
            'improvement_tips': '• Reducir gastos administrativos\n• Automatizar procesos\n• Mejorar productividad del personal\n• Renegociar contratos de servicios\n• Aumentar volumen de ventas con costos fijos similares',
            'sequence': 3,
        },
        {
            'name': 'ROE',
            'code': 'roe',
            'category': 'profitability',
            'formula': 'Ganancia Neta / Patrimonio Total × 100',
            'description': 'Mide cuánta ganancia genera la empresa por cada peso invertido por los accionistas. Indica qué tan bien se está usando el capital de los propietarios.',
            'unit': '%',
            'excellent_min': 20, 'excellent_max': 100,
            'excellent_description': 'Excelente: ROE superior al 20%. Excelente retorno para los accionistas.',
            'good_min': 10, 'good_max': 19.99,
            'good_description': 'Bueno: ROE entre 10-19%. Buen retorno, comparable a inversiones alternativas.',
            'fair_min': 5, 'fair_max': 9.99,
            'fair_description': 'Regular: ROE entre 5-9%. Retorno moderado, revisar rentabilidad.',
            'poor_min': -100, 'poor_max': 4.99,
            'poor_description': 'Deficiente: ROE menor al 5% o negativo. Considerar cambios estratégicos.',
            'improvement_tips': '• Aumentar ganancia neta\n• Reducir inversiones improductivas\n• Mejorar rotación de activos\n• Aumentar apalancamiento (deuda) estratégicamente\n• Revisar rentabilidad de productos/líneas de negocio',
            'sequence': 4,
        },
        {
            'name': 'ROA',
            'code': 'roa',
            'category': 'profitability',
            'formula': 'Ganancia Neta / Activos Totales × 100',
            'description': 'Mide cuánta ganancia genera cada peso de activos. Muestra la eficiencia con la que se usan los activos para generar ganancias.',
            'unit': '%',
            'excellent_min': 10, 'excellent_max': 100,
            'excellent_description': 'Excelente: ROA superior al 10%. Activos muy productivos.',
            'good_min': 5, 'good_max': 9.99,
            'good_description': 'Bueno: ROA entre 5-9%. Activos bien utilizados.',
            'fair_min': 2, 'fair_max': 4.99,
            'fair_description': 'Regular: ROA entre 2-4%. Activos subutilizados.',
            'poor_min': -100, 'poor_max': 1.99,
            'poor_description': 'Deficiente: ROA menor al 2% o negativo. Revisar uso de activos.',
            'improvement_tips': '• Aumentar ventas sin aumentar activos\n• Reducir activos improductivos\n• Mejorar rotación de inventarios\n• Acelerar cobro de cuentas por cobrar\n• Vender activos ociosos',
            'sequence': 5,
        },
        {
            'name': 'Razón Corriente',
            'code': 'current_ratio',
            'category': 'liquidity',
            'formula': 'Activos Circulantes / Pasivos Circulantes',
            'description': 'Mide la capacidad de la empresa para pagar sus deudas a corto plazo con activos circulantes. Indica liquidez inmediata.',
            'unit': 'veces',
            'excellent_min': 2, 'excellent_max': 5,
            'excellent_description': 'Excelente: Razón corriente entre 2-3. Empresa tiene buena liquidez y puede pagar deudas fácilmente.',
            'good_min': 1.5, 'good_max': 1.99,
            'good_description': 'Bueno: Razón corriente entre 1.5-1.9. Liquidez adecuada para operaciones.',
            'fair_min': 1, 'fair_max': 1.49,
            'fair_description': 'Regular: Razón corriente entre 1-1.4. Liquidez justa, monitoree efectivo.',
            'poor_min': 0, 'poor_max': 0.99,
            'poor_description': 'Deficiente: Razón corriente menor a 1. Empresa podría tener dificultades para pagar deudas a corto plazo.',
            'improvement_tips': '• Aumentar activos circulantes (caja, cobros)\n• Reducir pasivos circulantes (pagar deudas)\n• Acelerar cobros a clientes\n• Negociar plazos más largos con proveedores\n• Obtener financiamiento a largo plazo\n• Reducir inventarios obsoletos',
            'sequence': 6,
        },
        {
            'name': 'Prueba Ácida',
            'code': 'quick_ratio',
            'category': 'liquidity',
            'formula': '(Activos Circulantes - Inventarios) / Pasivos Circulantes',
            'description': 'Mide la capacidad de pagar deudas sin vender inventario. Más conservador que la razón corriente.',
            'unit': 'veces',
            'excellent_min': 1.5, 'excellent_max': 5,
            'excellent_description': 'Excelente: Prueba ácida superior a 1.5. Excelente liquidez inmediata.',
            'good_min': 1, 'good_max': 1.49,
            'good_description': 'Bueno: Prueba ácida entre 1-1.4. Liquidez adecuada sin dependencia de inventarios.',
            'fair_min': 0.5, 'fair_max': 0.99,
            'fair_description': 'Regular: Prueba ácida entre 0.5-0.9. Depende del inventario para liquidez.',
            'poor_min': 0, 'poor_max': 0.49,
            'poor_description': 'Deficiente: Prueba ácida menor a 0.5. Riesgo alto de liquidez.',
            'improvement_tips': '• Aumentar efectivo disponible\n• Reducir deudas a corto plazo\n• Acelerar cobranzas\n• Reducir inventarios excesivos\n• Obtener línea de crédito de emergencia\n• Refinanciar deudas a largo plazo',
            'sequence': 7,
        },
        {
            'name': 'Razón Deuda/Patrimonio',
            'code': 'debt_to_equity',
            'category': 'leverage',
            'formula': 'Pasivos Totales / Patrimonio Total',
            'description': 'Mide la relación entre deuda y capital propio. Indica el nivel de apalancamiento y riesgo financiero.',
            'unit': 'veces',
            'excellent_min': 0, 'excellent_max': 0.5,
            'excellent_description': 'Excelente: Razón D/E menor a 0.5. Empresa financiada principalmente con capital propio. Bajo riesgo.',
            'good_min': 0.5, 'good_max': 1.0,
            'good_description': 'Bueno: Razón D/E entre 0.5-1.0. Balance saludable entre deuda y capital.',
            'fair_min': 1.0, 'fair_max': 2.0,
            'fair_description': 'Regular: Razón D/E entre 1.0-2.0. Apalancamiento moderado, revisar capacidad de pago.',
            'poor_min': 2.0, 'poor_max': 100,
            'poor_description': 'Deficiente: Razón D/E superior a 2.0. Alto nivel de deuda, riesgo financiero elevado.',
            'improvement_tips': '• Aumentar capital de los accionistas\n• Pagar deudas con ganancias\n• Reducir gastos financieros\n• Aumentar rentabilidad\n• Refinanciar deudas a plazos más largos\n• Revender activos para reducir deuda',
            'sequence': 8,
        },
        {
            'name': 'Rotación de Activos',
            'code': 'asset_turnover',
            'category': 'efficiency',
            'formula': 'Ingresos Totales / Activos Totales',
            'description': 'Mide cuántas veces se vende el valor total de los activos. Indica la eficiencia en el uso de activos para generar ventas.',
            'unit': 'veces',
            'excellent_min': 2, 'excellent_max': 100,
            'excellent_description': 'Excelente: Rotación superior a 2. Activos muy productivos generando ventas.',
            'good_min': 1.5, 'good_max': 1.99,
            'good_description': 'Bueno: Rotación entre 1.5-1.9. Buen aprovechamiento de activos.',
            'fair_min': 0.8, 'fair_max': 1.49,
            'fair_description': 'Regular: Rotación entre 0.8-1.4. Activos moderadamente utilizados.',
            'poor_min': 0, 'poor_max': 0.79,
            'poor_description': 'Deficiente: Rotación menor a 0.8. Activos subutilizados o ineficientes.',
            'improvement_tips': '• Aumentar ventas sin aumentar activos\n• Mejorar eficiencia de inventarios\n• Acelerar cobros\n• Reducir activos ociosos\n• Optimizar uso de capacidad instalada\n• Vender o arrendar activos improductivos',
            'sequence': 9,
        },
    ]

    try:
        legend_model = env['indicator.legend']
        for legend_data in legends_data:
            existing = legend_model.search([('code', '=', legend_data['code'])])
            if not existing:
                legend_model.create(legend_data)
    except Exception as e:
        # Si hay error, continuar de todas formas
        pass

    return True
